### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by kwapik** [fluxninja/aperture-java#22]
The goal of this ticket is to improve documentation for Java SDK.
This should be achieved by:
1. Adding proper JavaDoc strings in the code.
2. Adding examples to README.md.
3. Adding short description about the SDK to README.md.

**Comment by tanveergill** [comment]
@kwapik, Is this done?

**Comment by kwapik** [comment]
@tanveergill surele this can be improved, but let's close for now
